name: CI/CD Operations

on:
  push:
    branches:
      - main
      - develop
jobs:
  build-infra:
    name: Build Infrastructure
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - run: |
          echo ${{secrets.CLIENTID}} | sed 's/./& /g'
          echo ${{secrets.REPOCLIENTID}} | sed 's/./& /g'
          echo ${{github.ref_slug}}
          echo ${{github.ref_name}}
          echo ${{github.ref}}
